/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/models/botWSkis/BotWSkisCopy.glb'
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // actions['backflip'].play();
    // actions['rotation'].play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0.01, 1.14, -0.2]}>
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh
              name="Alpha_Joints"
              geometry={nodes.Alpha_Joints.geometry}
              material={materials.Alpha_Joints_MAT}
              skeleton={nodes.Alpha_Joints.skeleton}
            />
          </group>
          <skinnedMesh
            name="Alpha_Surface"
            geometry={nodes.Alpha_Surface.geometry}
            material={materials.Alpha_Body_MAT}
            skeleton={nodes.Alpha_Surface.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/botWSkis/BotWSkisCopy.glb');
